# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import started_service_pb2 as started__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in started_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StartedServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/daemon.StartedService/GetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.Version.FromString,
                _registered_method=True)
        self.SubscribeServiceStatus = channel.unary_stream(
                '/daemon.StartedService/SubscribeServiceStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.ServiceStatus.FromString,
                _registered_method=True)
        self.SubscribeLog = channel.unary_stream(
                '/daemon.StartedService/SubscribeLog',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.Log.FromString,
                _registered_method=True)
        self.GetDefaultLogLevel = channel.unary_unary(
                '/daemon.StartedService/GetDefaultLogLevel',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.DefaultLogLevel.FromString,
                _registered_method=True)
        self.ClearLogs = channel.unary_unary(
                '/daemon.StartedService/ClearLogs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeStatus = channel.unary_stream(
                '/daemon.StartedService/SubscribeStatus',
                request_serializer=started__service__pb2.SubscribeStatusRequest.SerializeToString,
                response_deserializer=started__service__pb2.Status.FromString,
                _registered_method=True)
        self.SubscribeGroups = channel.unary_stream(
                '/daemon.StartedService/SubscribeGroups',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.Groups.FromString,
                _registered_method=True)
        self.GetClashModeStatus = channel.unary_unary(
                '/daemon.StartedService/GetClashModeStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.ClashModeStatus.FromString,
                _registered_method=True)
        self.SubscribeClashMode = channel.unary_stream(
                '/daemon.StartedService/SubscribeClashMode',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.ClashMode.FromString,
                _registered_method=True)
        self.SetClashMode = channel.unary_unary(
                '/daemon.StartedService/SetClashMode',
                request_serializer=started__service__pb2.ClashMode.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.URLTest = channel.unary_unary(
                '/daemon.StartedService/URLTest',
                request_serializer=started__service__pb2.URLTestRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SelectOutbound = channel.unary_unary(
                '/daemon.StartedService/SelectOutbound',
                request_serializer=started__service__pb2.SelectOutboundRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetGroupExpand = channel.unary_unary(
                '/daemon.StartedService/SetGroupExpand',
                request_serializer=started__service__pb2.SetGroupExpandRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TriggerOOMReport = channel.unary_unary(
                '/daemon.StartedService/TriggerOOMReport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeConnections = channel.unary_stream(
                '/daemon.StartedService/SubscribeConnections',
                request_serializer=started__service__pb2.SubscribeConnectionsRequest.SerializeToString,
                response_deserializer=started__service__pb2.ConnectionEvents.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/daemon.StartedService/CloseConnection',
                request_serializer=started__service__pb2.CloseConnectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CloseAllConnections = channel.unary_unary(
                '/daemon.StartedService/CloseAllConnections',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDeprecatedWarnings = channel.unary_unary(
                '/daemon.StartedService/GetDeprecatedWarnings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.DeprecatedWarnings.FromString,
                _registered_method=True)
        self.GetStartedAt = channel.unary_unary(
                '/daemon.StartedService/GetStartedAt',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.StartedAt.FromString,
                _registered_method=True)
        self.SubscribeOutbounds = channel.unary_stream(
                '/daemon.StartedService/SubscribeOutbounds',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.OutboundList.FromString,
                _registered_method=True)
        self.StartNetworkQualityTest = channel.unary_stream(
                '/daemon.StartedService/StartNetworkQualityTest',
                request_serializer=started__service__pb2.NetworkQualityTestRequest.SerializeToString,
                response_deserializer=started__service__pb2.NetworkQualityTestProgress.FromString,
                _registered_method=True)
        self.StartSTUNTest = channel.unary_stream(
                '/daemon.StartedService/StartSTUNTest',
                request_serializer=started__service__pb2.STUNTestRequest.SerializeToString,
                response_deserializer=started__service__pb2.STUNTestProgress.FromString,
                _registered_method=True)
        self.SubscribeTailscaleStatus = channel.unary_stream(
                '/daemon.StartedService/SubscribeTailscaleStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=started__service__pb2.TailscaleStatusUpdate.FromString,
                _registered_method=True)
        self.StartTailscalePing = channel.unary_stream(
                '/daemon.StartedService/StartTailscalePing',
                request_serializer=started__service__pb2.TailscalePingRequest.SerializeToString,
                response_deserializer=started__service__pb2.TailscalePingResponse.FromString,
                _registered_method=True)
        self.SetTailscaleExitNode = channel.unary_unary(
                '/daemon.StartedService/SetTailscaleExitNode',
                request_serializer=started__service__pb2.SetTailscaleExitNodeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TailscaleLogout = channel.unary_unary(
                '/daemon.StartedService/TailscaleLogout',
                request_serializer=started__service__pb2.TailscaleLogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StartTailscaleSSHSession = channel.stream_stream(
                '/daemon.StartedService/StartTailscaleSSHSession',
                request_serializer=started__service__pb2.TailscaleSSHClientMessage.SerializeToString,
                response_deserializer=started__service__pb2.TailscaleSSHServerMessage.FromString,
                _registered_method=True)


class StartedServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultLogLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClashModeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeClashMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetClashMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def URLTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectOutbound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGroupExpand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerOOMReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseAllConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeprecatedWarnings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartedAt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOutbounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartNetworkQualityTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSTUNTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTailscaleStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTailscalePing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTailscaleExitNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TailscaleLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTailscaleSSHSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StartedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.Version.SerializeToString,
            ),
            'SubscribeServiceStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeServiceStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.ServiceStatus.SerializeToString,
            ),
            'SubscribeLog': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeLog,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.Log.SerializeToString,
            ),
            'GetDefaultLogLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultLogLevel,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.DefaultLogLevel.SerializeToString,
            ),
            'ClearLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearLogs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeStatus,
                    request_deserializer=started__service__pb2.SubscribeStatusRequest.FromString,
                    response_serializer=started__service__pb2.Status.SerializeToString,
            ),
            'SubscribeGroups': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeGroups,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.Groups.SerializeToString,
            ),
            'GetClashModeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClashModeStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.ClashModeStatus.SerializeToString,
            ),
            'SubscribeClashMode': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeClashMode,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.ClashMode.SerializeToString,
            ),
            'SetClashMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetClashMode,
                    request_deserializer=started__service__pb2.ClashMode.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'URLTest': grpc.unary_unary_rpc_method_handler(
                    servicer.URLTest,
                    request_deserializer=started__service__pb2.URLTestRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SelectOutbound': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectOutbound,
                    request_deserializer=started__service__pb2.SelectOutboundRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetGroupExpand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGroupExpand,
                    request_deserializer=started__service__pb2.SetGroupExpandRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerOOMReport': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerOOMReport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeConnections': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeConnections,
                    request_deserializer=started__service__pb2.SubscribeConnectionsRequest.FromString,
                    response_serializer=started__service__pb2.ConnectionEvents.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=started__service__pb2.CloseConnectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CloseAllConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseAllConnections,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDeprecatedWarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeprecatedWarnings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.DeprecatedWarnings.SerializeToString,
            ),
            'GetStartedAt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartedAt,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.StartedAt.SerializeToString,
            ),
            'SubscribeOutbounds': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOutbounds,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.OutboundList.SerializeToString,
            ),
            'StartNetworkQualityTest': grpc.unary_stream_rpc_method_handler(
                    servicer.StartNetworkQualityTest,
                    request_deserializer=started__service__pb2.NetworkQualityTestRequest.FromString,
                    response_serializer=started__service__pb2.NetworkQualityTestProgress.SerializeToString,
            ),
            'StartSTUNTest': grpc.unary_stream_rpc_method_handler(
                    servicer.StartSTUNTest,
                    request_deserializer=started__service__pb2.STUNTestRequest.FromString,
                    response_serializer=started__service__pb2.STUNTestProgress.SerializeToString,
            ),
            'SubscribeTailscaleStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTailscaleStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=started__service__pb2.TailscaleStatusUpdate.SerializeToString,
            ),
            'StartTailscalePing': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTailscalePing,
                    request_deserializer=started__service__pb2.TailscalePingRequest.FromString,
                    response_serializer=started__service__pb2.TailscalePingResponse.SerializeToString,
            ),
            'SetTailscaleExitNode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTailscaleExitNode,
                    request_deserializer=started__service__pb2.SetTailscaleExitNodeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TailscaleLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.TailscaleLogout,
                    request_deserializer=started__service__pb2.TailscaleLogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StartTailscaleSSHSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StartTailscaleSSHSession,
                    request_deserializer=started__service__pb2.TailscaleSSHClientMessage.FromString,
                    response_serializer=started__service__pb2.TailscaleSSHServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daemon.StartedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daemon.StartedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StartedService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/GetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.Version.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeServiceStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeLog',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.Log.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefaultLogLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/GetDefaultLogLevel',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.DefaultLogLevel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/ClearLogs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeStatus',
            started__service__pb2.SubscribeStatusRequest.SerializeToString,
            started__service__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeGroups',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.Groups.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClashModeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/GetClashModeStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.ClashModeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeClashMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeClashMode',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.ClashMode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetClashMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/SetClashMode',
            started__service__pb2.ClashMode.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def URLTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/URLTest',
            started__service__pb2.URLTestRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectOutbound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/SelectOutbound',
            started__service__pb2.SelectOutboundRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGroupExpand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/SetGroupExpand',
            started__service__pb2.SetGroupExpandRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerOOMReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/TriggerOOMReport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeConnections',
            started__service__pb2.SubscribeConnectionsRequest.SerializeToString,
            started__service__pb2.ConnectionEvents.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/CloseConnection',
            started__service__pb2.CloseConnectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseAllConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/CloseAllConnections',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeprecatedWarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/GetDeprecatedWarnings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.DeprecatedWarnings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStartedAt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/GetStartedAt',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.StartedAt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeOutbounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeOutbounds',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.OutboundList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartNetworkQualityTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/StartNetworkQualityTest',
            started__service__pb2.NetworkQualityTestRequest.SerializeToString,
            started__service__pb2.NetworkQualityTestProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSTUNTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/StartSTUNTest',
            started__service__pb2.STUNTestRequest.SerializeToString,
            started__service__pb2.STUNTestProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTailscaleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/SubscribeTailscaleStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            started__service__pb2.TailscaleStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTailscalePing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daemon.StartedService/StartTailscalePing',
            started__service__pb2.TailscalePingRequest.SerializeToString,
            started__service__pb2.TailscalePingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTailscaleExitNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/SetTailscaleExitNode',
            started__service__pb2.SetTailscaleExitNodeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TailscaleLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daemon.StartedService/TailscaleLogout',
            started__service__pb2.TailscaleLogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTailscaleSSHSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/daemon.StartedService/StartTailscaleSSHSession',
            started__service__pb2.TailscaleSSHClientMessage.SerializeToString,
            started__service__pb2.TailscaleSSHServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
